# Generated by Django 4.2.4 on 2023-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_opscliusers_name_alter_opscliusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='assign_id',
            field=models.IntegerField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
